# docker-publish.yaml

name: Build and publish image to Docker Hub

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

      # https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        # with:
        #   submodules: true

      # https://github.com/docker/setup-buildx-action
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Identify pre-release
        id: pre
        run: |
          if [[ "$GITHUB_REF_NAME" =~ - ]]; then
            echo "is_prerelease=true" >> $GITHUB_OUTPUT
          else
            echo "is_prerelease=false" >> $GITHUB_OUTPUT
          fi

      # https://github.com/docker/metadata-action
      - name: Extract metadata for Docker Hub (all versions)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: setempler/debug-ninja
          tags: |
            type=semver,pattern={{version}}

      # https://github.com/docker/metadata-action
      - name: Extract metadata for Docker Hub (stable -> latest)
        if: steps.pre.outputs.is_prerelease == 'false'
        id: meta_stable
        uses: docker/metadata-action@v5
        with:
          images: setempler/debug-ninja
          tags: |
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=raw,value=latest

      # https://github.com/docker/login-action
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # https://github.com/docker/build-push-action
      - name: Build and push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ steps.meta_stable.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
